import Sidebar from '@/components/SideBar/Sidebar'
import '../styles/styles.css'
import ProfileBar from '@/components/NavBar/ProfileBar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ProfileBar/>
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}
