import Sidebar from '@/components/shared/SideBar/Sidebar'
import '../styles/styles.css'
import Box from '@/components/shared/Box/Box'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Box rows={[1,19]} columns={[1,2]}>
          <Sidebar/>
        </Box>
        <Box rows={[19,27]} columns={[1,2]}>
          
        </Box>
        <Box rows={[1,4]} columns={[2,17]}>
          
        </Box>
        <Box rows={[1,4]} columns={[17,19]}>
          
        </Box>
        <Box rows={[1,4]} columns={[19,21]}>
          
        </Box>
        <Box rows={[1,23]} columns={[21,27]}>
          
        </Box>
        <Box rows={[23,27]} columns={[21,27]}>
          
        </Box>
        {children}
      </body>
    </html>
  )
}
